# Schema for the configuration files of the Owl Carousel module.

owlcarousel.preset.*:
  type: config_entity
  label: 'Owl Carousel preset'
  mapping:
    name:
      type: string
    label:
      type: label
      label: 'Label'
    breakpoints:
      type: sequence
      label: 'Breakpoint configurations'
      sequence:
        - type: mapping
          label: 'Configuration'
          mapping:
            id:
              type: string
            data:
              type: mapping
              label: 'Owl Carousel preset per breakpoint'
              mapping:
                items:
                  type: integer
                  label: 'Items'
                loop:
                  type: boolean
                  label: 'Loop'
                center:
                  type: boolean
                  label: 'Center'