# Schema for the configuration files of the Owl Carousel module.

owlcarousel.preset.*:
  type: config_entity
  label: 'Owl Carousel preset'
  mapping:
    name:
      type: string
    label:
      type: label
      label: 'Label'
    breakpoints:
      type: sequence
      label: 'Breakpoint configurations'
      sequence:
        - type: mapping
          label: 'Configuration'
          mapping:
            id:
              type: string
            data:
              type: mapping
              label: 'Owl Carousel preset per breakpoint'
              mapping:
                items:
                  type: integer
                  label: 'Items'
                loop:
                  type: boolean
                  label: 'Loop'
                center:
                  type: boolean
                  label: 'Center'
                nav:
                  type: boolean
                  label: 'Navigation'
                dots:
                  type: boolean
                  label: 'Dots'
                nav_text_prev:
                  type: string
                  label: 'Nav text prev'
                nav_text_next:
                  type: string
                  label: 'Nav text next'
                mouseDrag:
                  type: boolean
                  label: 'Mouse Drag'
                touchDrag:
                  type: boolean
                  label: 'touch Drag'
                pullDrag:
                  type: boolean
                  label: 'boolean Drag'
                freeDrag:
                  type: boolean
                  label: 'Free Drag'
                stagePadding:
                  type: integer
                  label: 'Stage Padding'
                merge:
                  type: boolean
                  label: 'Merge'
                mergeFit:
                  type: boolean
                  label: 'Merge Fit'
                autoWidth:
                  type: boolean
                  label: 'Auto Width'
                autoHeight:
                  type: boolean
                  label: 'Auto height'
                navRewind:
                  type: boolean
                  label: 'Nav Rewind'
                slideBy:
                  type: integer
                  label: 'Slide By'
                dotsEach:
                  type: integer
                  label: 'Dots Each'
                autoplay:
                  type: boolean
                  label: 'Autoplay'
                autoplayTimeout:
                  type: integer
                  label: 'Autoplay Timeout'
                autoplaySpeed:
                  type: integer
                  label: 'Autoplay Speed'
                smartSpeed:
                  type: integer
                  label: 'Smart Speed'
                fluidSpeed:
                  type: integer
                  label: 'Fluid Speed'
                navSpeed:
                  type: integer
                  label: 'Navigation Speed'
                dotsSpeed:
                  type: integer
                  label: 'Dots Speed'
                dragEndSpeed:
                  type: integer
                  label: 'Drag End Speed'
                responsiveRefreshRate:
                  type: integer
                  label: 'Responsive Refresh Rate'
                animateOut:
                  type: boolean
                  label: 'Animate Out'
                animateIn:
                  type: boolean
                  label: 'Animate In'
                fallbackEasing:
                  type: string
                  label: 'Fallback Easing'
